# Generated by Django 4.1.3 on 2022-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
